pipeline:
    build:
        image: ubuntu:latest # Should be fine for most projects, alternatively use any other image from Docker Hub: https://hub.docker.com
        commands: 
            - apt-get update # Update apt index before installing packages
            - java -jar ManetClient.jar