pipeline:
    build:
        image: maven:3-jdk-7
        stage: build
        script: "mvn package -B"
        goal: clean install test
        artifacts:
            paths:
                - target/*.jar