pipeline:
    build:
        image: maven:3-jdk-7
        stage: compile
        script: "mvn package -B"
        goals: clean install test
        artifacts:
            paths:
                - target/*.jar